spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/nexosalud}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
  application:
    name: users-service
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
logging:
  level:
    org.springframework.data.r2dbc: Debug

server:
  port: ${SERVER_PORT:8081}

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/nexosalud
    username: postgres
    password: postgres
  application:
    name: users-service
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/nexosalud}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
  application:
    name: users-service
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: ${SERVER_PORT:8081}
