DROP TABLE IF EXISTS users ;
CREATE TABLE users (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	identification_type VARCHAR(2) NOT NULL,
	identification_number VARCHAR(15) NOT NULL,
	CONSTRAINT uq_users_identification UNIQUE (identification_type, identification_number)
);
DROP TABLE IF EXISTS attribute_user ;
CREATE TABLE attribute_user ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id integer, name_attribute VARCHAR(100) NOT NULL);
DROP TABLE IF EXISTS value_attribute_user ;
CREATE TABLE value_attribute_user ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,attribute_id integer, value_attribute VARCHAR(100) NOT NULL);