package com.reactive.nexo.test.controller;

import com.reactive.nexo.model.User;
import com.reactive.nexo.repository.UserRepository;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.http.MediaType;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.web.reactive.server.WebTestClient;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.springframework.test.web.reactive.server.EntityExchangeResult;


@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DirtiesContext
@AutoConfigureWebTestClient
@ActiveProfiles("test")
@Slf4j
public class UserControllerTest {

    @Autowired
    private WebTestClient webTestClient;

    @Autowired
    private UserRepository userRepository;


    @Autowired
    private DatabaseClient databaseClient;


    private List<User> getData(){
    return Arrays.asList(new User(null,"Suman", "Das","CC","0"),
        new User(null,"Arjun", "Das","CC","1"),
        new User(null,"Saurabh", "Ganguly","CC","2"));
    }

    @BeforeEach
    public  void setup(){
    List<String> statements = Arrays.asList(
    "DROP TABLE IF EXISTS value_attribute_user ;",
    "DROP TABLE IF EXISTS attribute_user ;",
    "DROP TABLE IF EXISTS users ;",
    "CREATE TABLE users ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, names VARCHAR(100) NOT NULL, lastnames VARCHAR(100) NOT NULL, identification_type VARCHAR(2) NOT NULL,identification_number VARCHAR(15) NOT NULL, CONSTRAINT uq_users_identification UNIQUE (identification_type, identification_number));",
    "CREATE TABLE attribute_user ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name_attribute VARCHAR(200) NOT NULL, user_id INT NOT NULL,multiple BOOLEAN DEFAULT FALSE, CONSTRAINT uq_users_attribute UNIQUE (user_id, name_attribute));",
    "CREATE TABLE value_attribute_user ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, attribute_id INT NOT NULL, value_attribute VARCHAR(500) NOT NULL);"
    );

    statements.forEach(it -> databaseClient.sql(it)
        .fetch()
        .rowsUpdated()
        .block());

    userRepository.deleteAll()
        .thenMany(Flux.fromIterable(getData()))
        .flatMap(userRepository::save)
        .doOnNext(user ->{
            System.out.println("User Inserted from UserControllerTest: " + user);
        })
        .blockLast();

    // insert one attribute and one value for user id 1 (to validate /by-identification endpoint)
    databaseClient.sql("INSERT INTO attribute_user (name_attribute, user_id) VALUES ('fecha de nacimiento', 1)")
        .fetch().rowsUpdated().block();

    Integer attrId = databaseClient.sql("SELECT id FROM attribute_user WHERE user_id = 1 AND name_attribute = 'fecha de nacimiento'")
        .map((row, metadata) -> {
            Number n = row.get("id", Number.class);
            return (n == null) ? null : n.intValue();
        })
        .one().block();

    if(attrId != null){
        databaseClient.sql("INSERT INTO value_attribute_user (attribute_id, value_attribute) VALUES (" + attrId + ", '1992-05-06')")
            .fetch().rowsUpdated().block();
    }

    }

    @Test
    public void getAllUsersValidateCount(){
        webTestClient.get().uri("/api/v1/users").exchange()
                .expectStatus().isOk()
                .expectHeader().contentType(MediaType.APPLICATION_JSON_VALUE)
                .expectBodyList(User.class)
                .hasSize(3)
                .consumeWith(user ->{
                    List<User> users = user.getResponseBody();
                    users.forEach( u ->{
                        assertTrue(u.getId() != null);
                    });
                });
    }
    @Test
    public void getAllUsersValidateResponse(){
        Flux<User> userFlux = webTestClient.get().uri("/api/v1/users").exchange()
                .expectStatus().isOk()
                .expectHeader().contentType(MediaType.APPLICATION_JSON_VALUE)
                .returnResult(User.class)
                .getResponseBody();
        StepVerifier.create(userFlux.log("Receiving values !!!"))
                .expectNextCount(3)
                .verifyComplete();

    }
    @Test
    public void getUserById(){
        webTestClient.get().uri("/api/v1/users".concat("/{userId}"),"1")
                            .exchange().expectStatus().isOk()
                            .expectBody()
                            .jsonPath("$.name","Suman Das");
    }
    @Test
    public void getUserById_NotFound(){
        webTestClient.get().uri("/api/v1/users".concat("/{userId}"),"6")
                .exchange().expectStatus().isNotFound();
    }
    @Test
    public void createUser(){
        User user = new User(null,"Rahul", "Dravid","CC","10");
        webTestClient.post().uri("/api/v1/users").contentType(MediaType.valueOf(MediaType.APPLICATION_JSON_VALUE))
                            .body(Mono.just(user),User.class)
                            .exchange()
                            .expectStatus().isCreated()
                            .expectBody()
                            .jsonPath("$.id").isNotEmpty()
                            .jsonPath("$.names").isEqualTo("Rahul")
                            .jsonPath("$.lastnames").isEqualTo("Dravid");
    }
    @Test
    public void deleteUser(){
        webTestClient.delete().uri("/api/v1/users".concat("/{userId}"),"1")
                     .accept(MediaType.valueOf(MediaType.APPLICATION_JSON_VALUE))
                     .exchange()
                     .expectStatus().isOk()
                     .expectBody(Void.class);
    }

    @Test
    public void getUserByIdentification_ReturnsAttributes(){
        webTestClient.get().uri("/api/v1/users/by-identification/{identificationType}/{identificationNumber}","CC","0")
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$.attributes[0].attribute_name").isEqualTo("fecha de nacimiento")
                .jsonPath("$.attributes[0].values[0]").isEqualTo("1992-05-06");
    }

    @Test
    public void createUserWithAttributes() throws Exception{
    String json = "{\n" +
        "  \"names\": \"Jhonn\",\n" +
        "  \"lastnames\": \"Campo\",\n" +
        "  \"identification_type\": \"CC\",\n" +
        "  \"identification_number\": \"858585\",\n" +
        "  \"attributes\": {\n" +
        "    \"fecha de nacimiento\": [\"1992-05-06\"],\n" +
        "    \"lugar de nacimiento ciudad\": [\"cali\"]\n" +
        "  }\n" +
        "}";

    EntityExchangeResult<User> res = webTestClient.post().uri("/api/v1/users")
        .contentType(MediaType.APPLICATION_JSON)
        .bodyValue(json)
        .exchange()
        .expectStatus().isCreated()
        .expectBody(User.class)
        .returnResult();

    User created = res.getResponseBody();
    assertNotNull(created);
    assertNotNull(created.getId());

    Integer userId = created.getId();

    Integer attrCount = databaseClient.sql("SELECT COUNT(*) AS c FROM attribute_user WHERE user_id = $1")
        .bind(0, userId)
        .map((row, md) -> {
            Number n = row.get("c", Number.class);
            return (n == null) ? null : n.intValue();
        })
        .one().block();

    assertEquals(2, attrCount.intValue());

    Integer valCount = databaseClient.sql("SELECT COUNT(*) AS c FROM value_attribute_user v JOIN attribute_user a ON a.id = v.attribute_id WHERE a.user_id = $1")
        .bind(0, userId)
        .map((row, md) -> {
            Number n = row.get("c", Number.class);
            return (n == null) ? null : n.intValue();
        })
        .one().block();
    assertEquals(2, valCount.intValue());
    }

    @Test
    public void updateUserAttributes_replaceAndAdd() throws Exception{
    // update user 1: replace fecha de nacimiento and add new attribute
    String json = "{\n" +
        "  \"names\": \"Suman\",\n" +
        "  \"lastnames\": \"Das\",\n" +
        "  \"identification_type\": \"CC\",\n" +
        "  \"identification_number\": \"0\",\n" +
        "  \"attributes\": {\n" +
        "    \"fecha de nacimiento\": [\"2000-01-01\"],\n" +
        "    \"nuevo atributo\": [\"valor1\"]\n" +
        "  }\n" +
        "}";

    webTestClient.put().uri("/api/v1/users/{id}", 1)
        .contentType(MediaType.APPLICATION_JSON)
        .bodyValue(json)
        .exchange()
        .expectStatus().isOk()
        .expectBody()
        .jsonPath("$.id").isEqualTo(1);

    // verify fecha de nacimiento updated
    Integer attrId = databaseClient.sql("SELECT id FROM attribute_user WHERE user_id = $1 AND name_attribute = $2")
        .bind(0, 1)
        .bind(1, "fecha de nacimiento")
        .map((r,m) -> {
            Number n = r.get("id", Number.class);
            return (n == null) ? null : n.intValue();
        })
        .one().block();

    Integer valCount = databaseClient.sql("SELECT COUNT(*) AS c FROM value_attribute_user WHERE attribute_id = $1")
        .bind(0, attrId)
        .map((r,m) -> {
            Number n = r.get("c", Number.class);
            return (n == null) ? null : n.intValue();
        })
        .one().block();
    assertEquals(1, valCount.intValue());

    String val = databaseClient.sql("SELECT value_attribute FROM value_attribute_user WHERE attribute_id = $1")
        .bind(0, attrId)
        .map((r,m) -> r.get("value_attribute", String.class))
        .one().block();
    assertEquals("2000-01-01", val);

    // verify new attribute exists
    Integer newAttrId = databaseClient.sql("SELECT id FROM attribute_user WHERE user_id = $1 AND name_attribute = $2")
        .bind(0, 1)
        .bind(1, "nuevo atributo")
        .map((r,m) -> {
            Number n = r.get("id", Number.class);
            return (n == null) ? null : n.intValue();
        })
        .one().block();
    assertNotNull(newAttrId);
    }
}
